// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw5ZoA8zau-Atkl56OtoYyWgT9ab7hgBo',
    appId: '1:1085231508379:web:bcbd310c2f9228396d8f3e',
    messagingSenderId: '1085231508379',
    projectId: 'my-ecommerce-app-123-39035',
    authDomain: 'my-ecommerce-app-123-39035.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-123-39035.firebasestorage.app',
    measurementId: 'G-Y0V1GKM7QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh1q07WLJaTlF-G_CYGyYbShajVoFQPQ0',
    appId: '1:1085231508379:android:fb290fb5e70342346d8f3e',
    messagingSenderId: '1085231508379',
    projectId: 'my-ecommerce-app-123-39035',
    storageBucket: 'my-ecommerce-app-123-39035.firebasestorage.app',
  );
}
